### ISSUE TITLE
Не получается запустить

### ISSUE THREAD

**Issue by kosichok** [dev0x13/telegram-chat-summarizer#1]
Здравствуйте. Никак не могу заставить работать telegram-chat-summarizer из статьи https://habr.com/ru/articles/804111/

При запуске по инструкции через докер:
![Docker_Desktop_hcw1cjQWkg](https://github.com/user-attachments/assets/2dedae3c-f072-421e-bef6-78d19c14f040)

При замене "bot.py" на "app.py" в Dockerfile:
![Docker_Desktop_o9G6UHxjM5](https://github.com/user-attachments/assets/12c8e593-1daa-448b-bc76-7698a864b6b7)
 

Смог запустить в докере на версии питона 3.8 (иначе библиотеки выдают ошибки). Содержимое консоли при запуске: ![Docker_Desktop_GKsypzU6Sw](https://github.com/user-attachments/assets/42b813e1-f367-495f-8f66-a257705f9a2e)
2024-09-25 00:18:20 2024-09-24 21:18:20,517 - INFO - Started!
2024-09-25 00:18:21 2024-09-24 21:18:21,523 - INFO - Running summarization job for: 1246948235

Бот в телеграмм при этом отвечает, но выжимку не присылает. При передаче контекста отвечает "No context is available for 1246948235 yet". В консоли в этот момент никаких изменений
![Telegram_XVTFyDSCfo](https://github.com/user-attachments/assets/929481ea-703c-4239-9d06-649e27d7d56c)

Очень хочу написать свою программу на базе вашего туториала, но к сожалению, мне не хватает навыков чтобы разобраться.
Если у вас есть идеи в чем может быть проблема, то я был бы очень благодарен за подсказку :)

**Comment by dev0x13** [comment]
Добрый день!
Спасибо за обратную связь! Докер образ действительно протух, так как был сделан небрежно. Этот момент я поправил.
Что касается отсутствия выжимки, то судя по логам, все работает корректно, просто суммаризация может занимать достаточно длительное время если текст для суммаризации объемный. Я бы попробовал подождать несколько минут и/или уменьшить параметр конфига `lookback_period_seconds`, чтобы уменьшить количество сообщений в истории чата для суммаризации.
Кроме того, можно попробовать запустить Докер контейнер с параметром `--network=host` - такое поведение может быть результатом проблем с подключением.
Дайте знать, если не поможет - будем разбираться!

**Comment by kosichok** [comment]
Получилось. Получается, проблема была в том что не на той версии питона запускал, теперь все работает. Спасибо большое!
